### ISSUE TITLE
Cron Job For Nags

### ISSUE THREAD

**Issue by dbeattie** [dbeattie/nag-me#71]
- Needs to query the DB for end_dates
- Then if end_date is still in the future, create a new nag with a 'false' boolean
- That false boolean is what the user will mark true if they practice that day
- If they don't, then the Twilio Cron will text message friends saying 'the didn't 'run 30 minutes today' or whatever they are doing to try and keep themselves accountable.

**Comment by Don-Stevenson** [comment]
completed
