### ISSUE TITLE
Queries for SMS Cron Jobs

### ISSUE THREAD

**Issue by dbeattie** [dbeattie/nag-me#74]
Query the DB for any nags that are 'false' on the current date(at the current time?). 

- This will be plugged into the SMS Cron job to text people at 6AM to remind them to do something
- It will also be plugged into the SMS Cron job to text friends at midnight that people didn't complete their nag for that day. Perhaps a more reasonable time for this text would be appropriate? 

_Maybe we should just do 2 queries around 6/7AM EST???_

**Comment by Don-Stevenson** [comment]
Completed this
